# Generated by Django 5.2.8 on 2025-11-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient identifier from Clinical Microservice', max_length=50)),
                ('report_date', models.DateField(help_text='Date of the report')),
                ('test_type', models.CharField(help_text='Type of genetic test performed', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('COMPLETED', 'Completed'), ('AMENDED', 'Amended')], default='DRAFT', help_text='Report status', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Report',
                'verbose_name_plural': 'Patient Reports',
                'db_table': 'patient_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zygosity', models.CharField(choices=[('HETEROZYGOUS', 'Heterozygous'), ('HOMOZYGOUS', 'Homozygous'), ('HEMIZYGOUS', 'Hemizygous')], help_text='Zygosity status', max_length=20)),
                ('allele_frequency', models.DecimalField(decimal_places=4, help_text='Variant allele frequency (0.0 to 1.0)', max_digits=5)),
                ('coverage', models.IntegerField(help_text='Sequencing coverage depth')),
                ('interpretation', models.TextField(help_text='Clinical interpretation of this variant for this patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Associated report', on_delete=django.db.models.deletion.CASCADE, related_name='report_variants', to='reports.patientreport')),
                ('variant', models.ForeignKey(help_text='Detected variant', on_delete=django.db.models.deletion.CASCADE, related_name='variant_reports', to='variants.variant')),
            ],
            options={
                'verbose_name': 'Report Variant',
                'verbose_name_plural': 'Report Variants',
                'db_table': 'report_variants',
                'ordering': ['report', 'variant'],
                'unique_together': {('report', 'variant')},
            },
        ),
    ]
