# Generated by Django 5.2.8 on 2025-11-30 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(help_text='Chromosome (e.g., chr17)', max_length=10)),
                ('position', models.BigIntegerField(help_text='Position on chromosome')),
                ('reference_base', models.CharField(help_text='Reference base(s) (e.g., A)', max_length=500)),
                ('alternate_base', models.CharField(help_text='Alternate base(s) (e.g., G)', max_length=500)),
                ('impact', models.CharField(choices=[('MISSENSE', 'Missense'), ('NONSENSE', 'Nonsense'), ('FRAMESHIFT', 'Frameshift'), ('SILENT', 'Silent'), ('SPLICE_SITE', 'Splice Site'), ('INFRAME_INSERTION', 'Inframe Insertion'), ('INFRAME_DELETION', 'Inframe Deletion')], help_text='Variant impact type', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(help_text='Associated gene', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genes.gene')),
            ],
            options={
                'db_table': 'genetic_variants',
                'ordering': ['chromosome', 'position'],
            },
        ),
    ]
