# Generated by Django 5.2.8 on 2025-11-30 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genetic_variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Patient ID from Clinical Microservice', max_length=50)),
                ('detection_date', models.DateField(help_text='Date variant was detected')),
                ('allele_frequency', models.DecimalField(decimal_places=4, help_text='Variant Allele Frequency (VAF) - 0.0 to 1.0', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(help_text='Detected variant', on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='genetic_variants.geneticvariant')),
            ],
            options={
                'db_table': 'patient_variant_reports',
                'ordering': ['-detection_date'],
            },
        ),
    ]
