# Generated by Django 5.2.8 on 2025-11-30 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='Variant nomenclature (e.g., c.2573T>G, p.Leu858Arg)', max_length=100)),
                ('variant_type', models.CharField(choices=[('SNV', 'Single Nucleotide Variant'), ('INSERTION', 'Insertion'), ('DELETION', 'Deletion'), ('INDEL', 'Insertion-Deletion'), ('CNV', 'Copy Number Variant'), ('FUSION', 'Gene Fusion')], help_text='Type of genetic variant', max_length=20)),
                ('chromosome_position', models.CharField(help_text='Chromosomal position (e.g., chr17:41234470)', max_length=50)),
                ('reference_allele', models.CharField(help_text='Reference nucleotide sequence', max_length=500)),
                ('alternate_allele', models.CharField(help_text='Alternate nucleotide sequence', max_length=500)),
                ('clinical_significance', models.CharField(choices=[('PATHOGENIC', 'Pathogenic'), ('LIKELY_PATHOGENIC', 'Likely Pathogenic'), ('UNCERTAIN', 'Uncertain Significance'), ('LIKELY_BENIGN', 'Likely Benign'), ('BENIGN', 'Benign')], help_text='Clinical significance classification', max_length=20)),
                ('effect_description', models.TextField(help_text='Description of the variant effect')),
                ('dbsnp_id', models.CharField(blank=True, help_text='dbSNP identifier (e.g., rs121913227)', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='dbSNP ID must start with "rs" followed by numbers', regex='^rs\\d+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gene', models.ForeignKey(help_text='Associated gene', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genes.gene')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'db_table': 'variants',
                'ordering': ['gene__gene_symbol', 'variant_name'],
                'unique_together': {('gene', 'variant_name')},
            },
        ),
    ]
