# Generated by Django 5.2.8 on 2025-11-30 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(help_text='Official gene symbol (e.g., BRCA1, TP53)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Gene symbol must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9-]+$')])),
                ('gene_name', models.CharField(help_text='Full gene name', max_length=255)),
                ('chromosome', models.CharField(help_text='Chromosome location (e.g., 17, X, Y)', max_length=10)),
                ('function', models.TextField(help_text='Gene function description')),
                ('oncological_relevance', models.TextField(help_text='Relevance in oncology')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
                'db_table': 'genes',
                'ordering': ['gene_symbol'],
            },
        ),
    ]
