# Generated by Django 5.2.8 on 2025-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Gene symbol (e.g., BRCA1)', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full gene name', max_length=255)),
                ('function_summary', models.TextField(help_text='Summary of gene function')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genes',
                'ordering': ['symbol'],
            },
        ),
    ]
